version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-minor-and-patch-dependency-updates:
        applies-to: version-updates
        patterns:
          - "*"
        # # Dependabot will still raise individual pull requests for updates to these excluded dependencies.
        exclude-patterns: 
          - "dash"
          - "dash-ag-grid"
          - "dash-bootstrap-components"
          - "dash_molstar"
          - "biopython"
          - "rdkit"
          - "plotly-express"
        update-types:
          - "minor"
          - "patch"
