app-mode: "disk"
#app-mode: "db"

# 5-letter code required for application functionality
# MUST be exactly 5 letters - set this value in your deployment
five_letter_id_prefix: ""

disk:
  # ---------------------------------
  # VALUES BELOW ONLY USED FOR app-mode: "disk"
  # ---------------------------------

  # use this for loading from disk
  # these files MUST be embedded in the repo for the docker file to work
  # define from package root (levseq_dash) here, don't put a '/' at the beginning

  # ----- use this for loading the test-data in dev mode
  #data_path: "app/tests/test_data/data"

  # ----- use this for loading the playground-mode data
  #data_path: "app/data/DEDB"

  # in playground mode uploading new experiments or
  # deleting current experiments is disabled
  enable_data_modification: false

# use these settings for db
db:
  host: ""
  port: 8051

# set to true to enable or disable parallel sequence alignment
parallel_sequence_alignment: false  # or false

logging:
  # set to true to enable profiling for performance testing
  # default for production should be false
  sequence_alignment_profiling: false  # or false

  pairwise_aligner: false  # or false

  # set to true to enable profiling for reading data in playground mode
  # default for production should be false
  data_manager: false